[package]
name = "metricsrbx/election-system"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Fusion = "elttob/fusion@0.2.0"